name: Build and Deploy Flutter Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'

      - run: flutter pub get

      # Check for web/index.html
      - name: Check index.html
        run: |
          if [ ! -f "web/index.html" ]; then
            echo "Error: web/index.html not found!"
            exit 1
          fi

      - name: Build Web
        run: flutter build web

      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Create release only for tags
        with:
          files: |
            build/web/*
          tag_name: ${{ github.ref }} 
          name: Release ${{ github.ref }}
          body: Automated release from GitHub Actions.
      - name: Pinky Flutter
        # You may pin to the exact commit or the version.
        # uses: rexthecoder/Pinky@c495e71691032166b557145005968ac2ac7e9032
        uses: rexthecoder/Pinky@v2.0.0
        with:
          # Flutter version
          flutter_version: '3.3.3'
          # Flutter channel
