name: Build 🐧📻 Deploy

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'
      - run: flutter pub get

      # Check for web/index.html
      - name: Check index.html
        run: |
          if [ ! -f "web/index.html" ]; then
            echo "Error: web/index.html not found!"
            exit 1
          fi

      - name: Build Web
        run: flutter build web

      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Create release only for tags
        with:
          files: |
            build/web/*
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automated release from GitHub Actions.
      - name: Setup Dart SDK
        # You may pin to the exact commit or the version.
        # uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
        uses: dart-lang/setup-dart@v1.6.4
        with:
          # This can be either the channel to install (i.e., 'stable', 'beta', 'dev'), an SDK release version (i.e., '2.19', '3.1'), or a specific SDK version (i.e, '2.19.1', '3.0.0-1.4.beta').
          sdk: 'stable'
          # The CPU architecture ('x64', 'ia32', 'arm', or 'arm64').
          # architecture: # optional
          # The build flavor ('release' or 'raw').
          flavor: 'release'
                
